# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: SuperLattice 非常格子
  zh: SuperLattice 非常格子
email: a.p.moore@ucl.ac.uk
description:
# Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  en: Collected writings to help me crystallise my thoughts and ideas. Hopefully, a transition from a disordered to a (slightly) more ordered state. <br> <br> This post is provided as Creative Commons Attribution-ShareAlike 4.0 International <br> by the original author, A P Moore.
  zh: 收集的著作可以帮助我明确自己的思想和观念。 我们希望，从一个过渡无序到（略）更有序的状态。<br> <br> 该帖子由原始作者 A P Moore 作为“知识共享署名-相同方式共享4.0”提供。
index:
  en:
  zh: 索引.html
feed:
  en: /feed.xml
  zh: /馈送.xml
baseurl: # the subpath of your site, e.g. /blog
url: "http://www.amaams.co.uk" # the base hostname & protocol for your site
twitter_username: latticecut
github_username:  latticecut

# Build settings
markdown: kramdown
